name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  stepA:
    runs-on: [self-hosted,Linux,X64]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: List containers
        run: |
          echo "Listing container processes:"
          docker ps -a
